[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
NEXT_PUBLIC_WEBAPP_URL = "${{NEXT_PUBLIC_WEBAPP_URL}}"
NEXT_PUBLIC_API_V2_URL = "${{NEXT_PUBLIC_API_V2_URL}}"
ORGANIZATIONS_ENABLED = "${{ORGANIZATIONS_ENABLED}}"
NEXT_PUBLIC_SINGLE_ORG_SLUG = "${{NEXT_PUBLIC_SINGLE_ORG_SLUG}}"
CALCOM_TELEMETRY_DISABLED = "1"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
CALENDSO_ENCRYPTION_KEY = "${{CALENDSO_ENCRYPTION_KEY}}"
DATABASE_URL = "${{DATABASE_URL}}"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
