/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { metadata as applecalendar__metadata_ts } from "./applecalendar/_metadata";
import { metadata as caldavcalendar__metadata_ts } from "./caldavcalendar/_metadata";
import { metadata as dailyvideo__metadata_ts } from "./dailyvideo/_metadata";
import { metadata as googlecalendar__metadata_ts } from "./googlecalendar/_metadata";
import { metadata as googlevideo__metadata_ts } from "./googlevideo/_metadata";
import ics_feedcalendar_config_json from "./ics-feedcalendar/config.json";
import { metadata as office365calendar__metadata_ts } from "./office365calendar/_metadata";
import office365video_config_json from "./office365video/config.json";
import { metadata as stripepayment__metadata_ts } from "./stripepayment/_metadata";
import basic_config_json from "./templates/basic/config.json";
import booking_pages_tag_config_json from "./templates/booking-pages-tag/config.json";
import event_type_app_card_config_json from "./templates/event-type-app-card/config.json";
import event_type_location_video_static_config_json from "./templates/event-type-location-video-static/config.json";
import general_app_settings_config_json from "./templates/general-app-settings/config.json";
import link_as_an_app_config_json from "./templates/link-as-an-app/config.json";
import { metadata as zoomvideo__metadata_ts } from "./zoomvideo/_metadata";
export const appStoreMetadata = {
  applecalendar: applecalendar__metadata_ts,
  caldavcalendar: caldavcalendar__metadata_ts,
  dailyvideo: dailyvideo__metadata_ts,
  googlecalendar: googlecalendar__metadata_ts,
  googlevideo: googlevideo__metadata_ts,
  "ics-feedcalendar": ics_feedcalendar_config_json,
  office365calendar: office365calendar__metadata_ts,
  office365video: office365video_config_json,
  stripepayment: stripepayment__metadata_ts,
  basic: basic_config_json,
  "booking-pages-tag": booking_pages_tag_config_json,
  "event-type-app-card": event_type_app_card_config_json,
  "event-type-location-video-static": event_type_location_video_static_config_json,
  "general-app-settings": general_app_settings_config_json,
  "link-as-an-app": link_as_an_app_config_json,
  zoomvideo: zoomvideo__metadata_ts,
};
