/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const VideoApiAdapterMap =
  process.env.NEXT_PUBLIC_IS_E2E === "1"
    ? {}
    : {
        dailyvideo: import("./dailyvideo/lib/VideoApiAdapter"),
        office365video: import("./office365video/lib/VideoApiAdapter"),
        zoomvideo: import("./zoomvideo/lib/VideoApiAdapter"),
      };
